### ISSUE TITLE
Uncaught TypeError: $(...).ghostHunter is not a function(…)

### ISSUE THREAD

**Issue by ajmeyghani** [nehalist/ghoststa#2]
Thanks for the great and simple theme. For some reason, when I enable the theme it doesn't find `ghostHunter` plugin. Do I need to do anything else in addition to enabling the beta public api for it to work? Or do I need to manually install the GhostHunter plugin? Thanks!

> index.js?v=b6407a3c41:3 Uncaught TypeError: $(...).ghostHunter is not a function(…)

**Comment by nehalist** [comment]
You need to run `grunt build` in order to build the vendor files (see https://github.com/nehalist/ghoststa/blob/master/Gruntfile.js#L111). 

It probably would make sense to include these files in the repository so that non-developers or people who "just want to use it" doesn't have to do that. I'll take care of that during the holidays.
